### ISSUE TITLE
turn on logging for modernxmpp chat

### ISSUE THREAD

**Issue by pdurbin** [modernxmpp/modernxmpp#20]
As discussed at http://logs.xmpp.org/xsf/2019-05-02?p=h#2019-05-02-6f388f5dd60c01b5 @mwild1 would like to turn on logging for the modernxmpp room at rooms.modernxmpp.org.

**Comment by Zash** [comment]
- [x] Room archiving enabled
- [x] MAM available
- [x] Web archive access enabled in Prosody
- [ ] Domain like `logs.modernxmpp.org` set up
    - <https://chat.modernxmpp.org/log/> for now
- [x] Web archive access configured in httpd

**Comment by pdurbin** [comment]
@Zash @mwild1 thanks for doing so many things on the checklist above! 🎉 

Should we just stick with https://chat.modernxmpp.org/log/ instead of setting up https://logs.modernxmpp.org and close this issue?

**Comment by mwild1** [comment]
Yep, I think what we have is just fine. Thanks!
